#!/usr/bin/env bash

# Shared DB. Set these in your shell before running if you are using the shared LMS database.
export ZIVAI_DB_URL="${ZIVAI_DB_URL:-}"
export ZIVAI_DB_USERNAME="${ZIVAI_DB_USERNAME:-}"
export ZIVAI_DB_PASSWORD="${ZIVAI_DB_PASSWORD:-}"
export AUTO_CREATE_TABLES="${AUTO_CREATE_TABLES:-false}"

# MindSpore / model runtime.
export MS_DEVICE_TARGET="${MS_DEVICE_TARGET:-CPU}"
export MS_STRICT_DEVICE="${MS_STRICT_DEVICE:-true}"
export MS_MODE="${MS_MODE:-PYNATIVE_MODE}"
export MODEL_ID="${MODEL_ID:-Qwen/Qwen2.5-0.5B-Instruct}"
export MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"

# ASAG short-answer model artifacts.
export ASAG_ENABLED="${ASAG_ENABLED:-true}"
export ASAG_MODEL_DIR="${ASAG_MODEL_DIR:-$PWD/models/asag}"
export ASAG_CKPT_PATH="${ASAG_CKPT_PATH:-$ASAG_MODEL_DIR/asag_mohler_best.ckpt}"
export ASAG_MINDIR_PATH="${ASAG_MINDIR_PATH:-$ASAG_MODEL_DIR/asag_mohler.mindir}"
export ASAG_VOCAB_PATH="${ASAG_VOCAB_PATH:-$ASAG_MODEL_DIR/tokenizer/vocab.json}"
export ASAG_RESULTS_PATH="${ASAG_RESULTS_PATH:-$ASAG_MODEL_DIR/results.json}"
export ASAG_MAX_LENGTH="${ASAG_MAX_LENGTH:-256}"
export ASAG_HIDDEN_SIZE="${ASAG_HIDDEN_SIZE:-256}"
export ASAG_DROPOUT_PROB="${ASAG_DROPOUT_PROB:-0.2}"
export ASAG_RAW_SCORE_MAX="${ASAG_RAW_SCORE_MAX:-5.0}"
export ASAG_SHORT_ANSWER_MAX_MARKS="${ASAG_SHORT_ANSWER_MAX_MARKS:-5.0}"

# DKT artifacts and subject defaults.
export DKT_MODEL_DIR="${DKT_MODEL_DIR:-$PWD/models/dkt}"
export DKT_CLOUD_CKPT_PATH="${DKT_CLOUD_CKPT_PATH:-$DKT_MODEL_DIR/dkt_lstm_cloud.ckpt}"
export DKT_EDGE_MINDIR_PATH="${DKT_EDGE_MINDIR_PATH:-$DKT_MODEL_DIR/dkt_lstm_edge.mindir}"
export DKT_SKILL_MAP_PATH="${DKT_SKILL_MAP_PATH:-$DKT_MODEL_DIR/skill_map_v1.json}"
export DKT_MODEL_META_PATH="${DKT_MODEL_META_PATH:-$DKT_MODEL_DIR/model_meta.json}"
export DKT_DEFAULT_SUBJECT_CODE="${DKT_DEFAULT_SUBJECT_CODE:-computer_science}"
export DKT_WEAK_SKILL_LIMIT="${DKT_WEAK_SKILL_LIMIT:-5}"

# Huawei OCR credentials. Keep these out of git and inject them from your shell or secrets manager.
export HWC_AK="${HWC_AK:-}"
export HWC_SK="${HWC_SK:-}"
export HWC_PROJECT_ID="${HWC_PROJECT_ID:-}"

# Huawei OCR service defaults.
export HWC_OCR_ENDPOINT="${HWC_OCR_ENDPOINT:-https://ocr.ap-southeast-1.myhuaweicloud.com}"
export HWC_HOST="${HWC_HOST:-ocr.ap-southeast-1.myhuaweicloud.com}"
export HWC_FORCE_TRAILING_SLASH="${HWC_FORCE_TRAILING_SLASH:-false}"
export HWC_HTTP_TIMEOUT_SECONDS="${HWC_HTTP_TIMEOUT_SECONDS:-180}"
export HWC_GENERAL_TEXT_DETECT_DIRECTION="${HWC_GENERAL_TEXT_DETECT_DIRECTION:-true}"
export HWC_GENERAL_TEXT_QUICK_MODE="${HWC_GENERAL_TEXT_QUICK_MODE:-false}"
export HWC_GENERAL_TEXT_MAX_ORIGINAL_FILE_SIZE_BYTES="${HWC_GENERAL_TEXT_MAX_ORIGINAL_FILE_SIZE_BYTES:-7340032}"
export HWC_GENERAL_TEXT_MAX_ENCODED_IMAGE_BYTES="${HWC_GENERAL_TEXT_MAX_ENCODED_IMAGE_BYTES:-2500000}"
export HWC_GENERAL_TEXT_MAX_IMAGE_WIDTH="${HWC_GENERAL_TEXT_MAX_IMAGE_WIDTH:-2200}"
export HWC_GENERAL_TEXT_MAX_IMAGE_HEIGHT="${HWC_GENERAL_TEXT_MAX_IMAGE_HEIGHT:-2200}"
export HWC_GENERAL_TEXT_JPEG_QUALITY="${HWC_GENERAL_TEXT_JPEG_QUALITY:-0.72}"
export HWC_GENERAL_TEXT_MIN_JPEG_QUALITY="${HWC_GENERAL_TEXT_MIN_JPEG_QUALITY:-0.50}"
export HWC_GENERAL_TEXT_ADAPTIVE_RESIZE_PERCENT="${HWC_GENERAL_TEXT_ADAPTIVE_RESIZE_PERCENT:-85}"
export HWC_GENERAL_TEXT_MAX_ADAPTIVE_PASSES="${HWC_GENERAL_TEXT_MAX_ADAPTIVE_PASSES:-6}"
export HWC_GENERAL_TEXT_PDF_RENDER_DPI="${HWC_GENERAL_TEXT_PDF_RENDER_DPI:-200}"
export HWC_GENERAL_TEXT_MAX_PDF_PAGES="${HWC_GENERAL_TEXT_MAX_PDF_PAGES:-50}"
