#!/usr/bin/env bash

# Shared DB. Set these in your shell before running if you are using the shared LMS database.
export ZIVAI_DB_URL="${ZIVAI_DB_URL:-}"
export ZIVAI_DB_USERNAME="${ZIVAI_DB_USERNAME:-}"
export ZIVAI_DB_PASSWORD="${ZIVAI_DB_PASSWORD:-}"
export AUTO_CREATE_TABLES="${AUTO_CREATE_TABLES:-false}"

# MindSpore / model runtime.
export MS_DEVICE_TARGET="${MS_DEVICE_TARGET:-CPU}"
export MS_STRICT_DEVICE="${MS_STRICT_DEVICE:-true}"
export MS_MODE="${MS_MODE:-PYNATIVE_MODE}"
export MODEL_ID="${MODEL_ID:-Qwen/Qwen2.5-0.5B-Instruct}"
export MAX_NEW_TOKENS="${MAX_NEW_TOKENS:-128}"

# Huawei OCR credentials. Keep these out of git and inject them from your shell or secrets manager.
export HWC_AK="${HWC_AK:-}"
export HWC_SK="${HWC_SK:-}"
export HWC_PROJECT_ID="${HWC_PROJECT_ID:-}"

# Huawei OCR service defaults.
export HWC_OCR_ENDPOINT="${HWC_OCR_ENDPOINT:-https://ocr.ap-southeast-1.myhuaweicloud.com}"
export HWC_HOST="${HWC_HOST:-ocr.ap-southeast-1.myhuaweicloud.com}"
export HWC_FORCE_TRAILING_SLASH="${HWC_FORCE_TRAILING_SLASH:-false}"
export HWC_HTTP_TIMEOUT_SECONDS="${HWC_HTTP_TIMEOUT_SECONDS:-180}"
export HWC_GENERAL_TEXT_DETECT_DIRECTION="${HWC_GENERAL_TEXT_DETECT_DIRECTION:-true}"
export HWC_GENERAL_TEXT_QUICK_MODE="${HWC_GENERAL_TEXT_QUICK_MODE:-false}"
export HWC_GENERAL_TEXT_MAX_ORIGINAL_FILE_SIZE_BYTES="${HWC_GENERAL_TEXT_MAX_ORIGINAL_FILE_SIZE_BYTES:-7340032}"
export HWC_GENERAL_TEXT_MAX_ENCODED_IMAGE_BYTES="${HWC_GENERAL_TEXT_MAX_ENCODED_IMAGE_BYTES:-2500000}"
export HWC_GENERAL_TEXT_MAX_IMAGE_WIDTH="${HWC_GENERAL_TEXT_MAX_IMAGE_WIDTH:-2200}"
export HWC_GENERAL_TEXT_MAX_IMAGE_HEIGHT="${HWC_GENERAL_TEXT_MAX_IMAGE_HEIGHT:-2200}"
export HWC_GENERAL_TEXT_JPEG_QUALITY="${HWC_GENERAL_TEXT_JPEG_QUALITY:-0.72}"
export HWC_GENERAL_TEXT_MIN_JPEG_QUALITY="${HWC_GENERAL_TEXT_MIN_JPEG_QUALITY:-0.50}"
export HWC_GENERAL_TEXT_ADAPTIVE_RESIZE_PERCENT="${HWC_GENERAL_TEXT_ADAPTIVE_RESIZE_PERCENT:-85}"
export HWC_GENERAL_TEXT_MAX_ADAPTIVE_PASSES="${HWC_GENERAL_TEXT_MAX_ADAPTIVE_PASSES:-6}"
export HWC_GENERAL_TEXT_PDF_RENDER_DPI="${HWC_GENERAL_TEXT_PDF_RENDER_DPI:-200}"
export HWC_GENERAL_TEXT_MAX_PDF_PAGES="${HWC_GENERAL_TEXT_MAX_PDF_PAGES:-50}"
